// Package env handles environment variable resolution for Grove workspaces.
//
// Resolution order (last wins):
//  1. .env files — symlinked from main repo into worktrees
//  2. .env.local files — generated by grove with branch-specific port assignments
//  3. tmux set-environment — fallback for non-dotenv tools (session mode only)
package env

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/lukemelnik/grove/internal/config"
	"github.com/lukemelnik/grove/internal/proxy"
)

// templatePattern matches {{service.port}} and {{branch}} references in env values.
var templatePattern = regexp.MustCompile(`\{\{(\w+(?:\.\w+)?)\}\}`)

// ParseEnvFile reads a .env file and returns a map of key-value pairs.
// It handles:
//   - Empty lines (skipped)
//   - Comment lines starting with # (skipped)
//   - KEY=VALUE format
//   - Quoted values (single and double quotes are stripped)
//   - Inline comments after unquoted values
//   - Lines with no = sign (skipped)
func ParseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading env file %s: %w", path, err)
	}
	return ParseEnvContent(string(data))
}

// ParseEnvContent parses the content of a .env file (as a string) into key-value pairs.
func ParseEnvContent(content string) (map[string]string, error) {
	result := make(map[string]string)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Find the first = sign
		eqIdx := strings.Index(line, "=")
		if eqIdx < 0 {
			// No = sign, skip this line
			continue
		}

		key := strings.TrimSpace(line[:eqIdx])
		value := strings.TrimSpace(line[eqIdx+1:])

		if key == "" {
			continue
		}

		// Handle quoted values — preserve content inside quotes verbatim.
		// For unquoted values, strip inline comments (e.g., "value # comment").
		quoted := false
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
				quoted = true
			}
		}
		if !quoted {
			if idx := strings.Index(value, " #"); idx >= 0 {
				value = strings.TrimRight(value[:idx], " ")
			}
		}

		result[key] = value
	}

	return result, nil
}

// ProxyInfo holds the proxy configuration needed for template resolution.
type ProxyInfo struct {
	ProjectName   string
	Port          int
	HTTPS         bool
	DefaultBranch string
}

// ProxyInfoFromConfig constructs a ProxyInfo from a config's proxy section.
// Returns nil if proxyCfg is nil.
func ProxyInfoFromConfig(proxyCfg *config.ProxyConfig, projectRoot, defaultBranch string) *ProxyInfo {
	if proxyCfg == nil {
		return nil
	}
	name := proxyCfg.Name
	if name == "" {
		name = filepath.Base(filepath.Clean(projectRoot))
	}
	port := proxyCfg.Port
	if port == 0 {
		port = proxy.DefaultProxyPort
	}
	return &ProxyInfo{
		ProjectName:   name,
		Port:          port,
		HTTPS:         proxyCfg.HTTPS,
		DefaultBranch: defaultBranch,
	}
}

// BuildProxyURL builds the full proxy URL for a service.
func (pi *ProxyInfo) BuildProxyURL(service, branch string) (string, error) {
	hostname, err := proxy.BuildHostname(service, branch, pi.ProjectName, pi.DefaultBranch)
	if err != nil {
		return "", err
	}

	scheme := "http"
	if pi.HTTPS {
		scheme = "https"
	}

	defaultPort := 80
	if pi.HTTPS {
		defaultPort = 443
	}

	if pi.Port == defaultPort {
		return fmt.Sprintf("%s://%s", scheme, hostname), nil
	}
	return fmt.Sprintf("%s://%s:%d", scheme, hostname, pi.Port), nil
}

// BuildProxyHost builds just the proxy hostname for a service.
func (pi *ProxyInfo) BuildProxyHost(service, branch string) (string, error) {
	return proxy.BuildHostname(service, branch, pi.ProjectName, pi.DefaultBranch)
}

// ResolveTemplates replaces {{service.port}}, {{service.url}}, {{service.host}},
// and {{branch}} references in a string using the provided port map, branch name,
// and optional proxy info.
// Returns the resolved string and an error if any referenced template is unknown.
func ResolveTemplates(value string, ports map[string]int, branch string, proxyInfo *ProxyInfo) (string, error) {
	var resolveErr error

	resolved := templatePattern.ReplaceAllStringFunc(value, func(match string) string {
		submatch := templatePattern.FindStringSubmatch(match)
		if len(submatch) < 2 {
			return match
		}
		ref := submatch[1]

		if ref == "branch" {
			return branch
		}

		parts := strings.SplitN(ref, ".", 2)
		if len(parts) == 2 && parts[1] == "port" {
			port, ok := ports[parts[0]]
			if !ok {
				resolveErr = fmt.Errorf("unknown service %q in template %q", parts[0], match)
				return match
			}
			return fmt.Sprintf("%d", port)
		}

		if len(parts) == 2 && parts[1] == "url" {
			if proxyInfo == nil {
				resolveErr = fmt.Errorf("template %q requires proxy configuration", match)
				return match
			}
			urlStr, err := proxyInfo.BuildProxyURL(parts[0], branch)
			if err != nil {
				resolveErr = fmt.Errorf("building proxy URL for %q: %w", parts[0], err)
				return match
			}
			return urlStr
		}

		if len(parts) == 2 && parts[1] == "host" {
			if proxyInfo == nil {
				resolveErr = fmt.Errorf("template %q requires proxy configuration", match)
				return match
			}
			host, err := proxyInfo.BuildProxyHost(parts[0], branch)
			if err != nil {
				resolveErr = fmt.Errorf("building proxy hostname for %q: %w", parts[0], err)
				return match
			}
			return host
		}

		resolveErr = fmt.Errorf("unknown template %q", match)
		return match
	})

	return resolved, resolveErr
}

// ServiceManagedEnv describes the managed env vars for a single service.
type ServiceManagedEnv struct {
	Name    string
	EnvFile string
	PortKey string
	PortVal string
	Vars    map[string]string
}

// ManagedEnv groups global env vars, unique service port vars, and service-
// scoped env vars so runtime code can write .env.local files without losing
// service ownership.
type ManagedEnv struct {
	Global   map[string]string
	Services map[string]ServiceManagedEnv
}

// SessionEnv returns the session-wide env for tmux fallback injection.
// Only top-level env vars and service port vars are included here; service-
// scoped env vars stay in their service's .env.local file.
func (m *ManagedEnv) SessionEnv() map[string]string {
	result := make(map[string]string, len(m.Global)+len(m.Services))

	for k, v := range m.Global {
		result[k] = v
	}

	names := make([]string, 0, len(m.Services))
	for name := range m.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := m.Services[name]
		if svc.PortKey != "" && svc.PortVal != "" {
			result[svc.PortKey] = svc.PortVal
		}
	}

	return result
}

// EnvLocalMappings builds the .env.local write plan for all configured env
// files. Top-level env vars are written to every .env.local file. Service-
// scoped vars and service port vars are written only to that service's
// env_file.local. Port vars for services without env_file fall back to the
// top-level env_files list using key matching, then the last top-level env file.
func (m *ManagedEnv) EnvLocalMappings(cfg *config.Config, projectRoot string) ([]EnvLocalMapping, error) {
	allEnvFiles := cfg.AllEnvFiles()
	if len(allEnvFiles) == 0 {
		return nil, nil
	}

	mappingIndex := make(map[string]int)
	var mappings []EnvLocalMapping

	addToMapping := func(localPath, key, val string) {
		idx, exists := mappingIndex[localPath]
		if !exists {
			idx = len(mappings)
			mappingIndex[localPath] = idx
			mappings = append(mappings, EnvLocalMapping{RelPath: localPath, Vars: make(map[string]string)})
		}
		mappings[idx].Vars[key] = val
	}

	globalKeys := make([]string, 0, len(m.Global))
	for key := range m.Global {
		globalKeys = append(globalKeys, key)
	}
	sort.Strings(globalKeys)

	for _, envFile := range allEnvFiles {
		localPath := envFile + ".local"
		for _, key := range globalKeys {
			addToMapping(localPath, key, m.Global[key])
		}
	}

	names := make([]string, 0, len(m.Services))
	for name := range m.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	orphanPorts := make(map[string]string)
	for _, name := range names {
		svc := m.Services[name]

		if svc.EnvFile == "" {
			if svc.PortKey != "" && svc.PortVal != "" {
				orphanPorts[svc.PortKey] = svc.PortVal
			}
			continue
		}

		localPath := svc.EnvFile + ".local"
		if svc.PortKey != "" && svc.PortVal != "" {
			addToMapping(localPath, svc.PortKey, svc.PortVal)
		}

		keys := make([]string, 0, len(svc.Vars))
		for key := range svc.Vars {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			addToMapping(localPath, key, svc.Vars[key])
		}
	}

	if len(orphanPorts) > 0 && len(cfg.EnvFiles) > 0 {
		placed := make(map[string]bool)
		for _, envFile := range cfg.EnvFiles {
			absPath := envFile
			if projectRoot != "" && !filepath.IsAbs(absPath) {
				absPath = filepath.Join(projectRoot, absPath)
			}

			existing, err := ParseEnvFile(absPath)
			if err != nil {
				continue
			}

			localPath := envFile + ".local"
			for key, val := range orphanPorts {
				if placed[key] {
					continue
				}
				if _, inFile := existing[key]; inFile {
					addToMapping(localPath, key, val)
					placed[key] = true
				}
			}
		}

		lastLocal := cfg.EnvFiles[len(cfg.EnvFiles)-1] + ".local"
		orphanKeys := make([]string, 0, len(orphanPorts))
		for key := range orphanPorts {
			orphanKeys = append(orphanKeys, key)
		}
		sort.Strings(orphanKeys)
		for _, key := range orphanKeys {
			if !placed[key] {
				addToMapping(lastLocal, key, orphanPorts[key])
			}
		}
	}

	filtered := make([]EnvLocalMapping, 0, len(mappings))
	for _, mapping := range mappings {
		if len(mapping.Vars) == 0 {
			continue
		}
		filtered = append(filtered, mapping)
	}

	return filtered, nil
}

func resolveGlobalEnv(cfg *config.Config, ports map[string]int, branch string, proxyInfo *ProxyInfo) (map[string]string, error) {
	result := make(map[string]string)
	for k, v := range cfg.Env {
		resolved, err := ResolveTemplates(v, ports, branch, proxyInfo)
		if err != nil {
			return nil, fmt.Errorf("resolving template in env var %s: %w", k, err)
		}
		result[k] = resolved
	}
	return result, nil
}

// BuildManagedEnv resolves Grove-managed env vars while preserving service
// ownership for service-scoped values.
func BuildManagedEnv(cfg *config.Config, ports map[string]int, branch string, proxyInfo *ProxyInfo) (*ManagedEnv, error) {
	global, err := resolveGlobalEnv(cfg, ports, branch, proxyInfo)
	if err != nil {
		return nil, err
	}

	services := make(map[string]ServiceManagedEnv, len(cfg.Services))
	names := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := cfg.Services[name]
		entry := ServiceManagedEnv{
			Name:    name,
			EnvFile: svc.EnvFile,
			PortKey: svc.Port.Env,
			Vars:    make(map[string]string, len(svc.Env)),
		}

		if port, ok := ports[name]; ok {
			entry.PortVal = fmt.Sprintf("%d", port)
		}

		keys := make([]string, 0, len(svc.Env))
		for key := range svc.Env {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		for _, key := range keys {
			resolved, err := ResolveTemplates(svc.Env[key], ports, branch, proxyInfo)
			if err != nil {
				return nil, fmt.Errorf("resolving template in service %s env var %s: %w", name, key, err)
			}
			entry.Vars[key] = resolved
		}

		services[name] = entry
	}

	return &ManagedEnv{
		Global:   global,
		Services: services,
	}, nil
}

// Resolve computes the flattened environment variables for a worktree.
//
// Parameters:
//   - cfg: the parsed .grove.yml configuration
//   - ports: map of service name to assigned port (from port hashing)
//   - branch: the branch name (for {{branch}} template resolution)
//   - projectRoot: the project root directory (for resolving relative env file paths)
//
// Resolution order (last wins):
//  1. .env files from cfg.EnvFiles and service env_file fields
//  2. top-level env block (with template resolution)
//  3. service-level env blocks (with template resolution)
//  4. service port vars (e.g., PORT=4045)
func Resolve(cfg *config.Config, ports map[string]int, branch string, projectRoot string, proxyInfo *ProxyInfo) (map[string]string, error) {
	result := make(map[string]string)

	// Step 1: Read all .env files (order matters, later files override earlier ones)
	for _, envFile := range cfg.AllEnvFiles() {
		path := envFile
		if projectRoot != "" && !filepath.IsAbs(path) {
			path = filepath.Join(projectRoot, path)
		}
		vars, err := ParseEnvFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading env file: %w", err)
		}
		for k, v := range vars {
			result[k] = v
		}
	}

	managed, err := BuildManagedEnv(cfg, ports, branch, proxyInfo)
	if err != nil {
		return nil, err
	}

	for k, v := range managed.Global {
		result[k] = v
	}

	names := make([]string, 0, len(managed.Services))
	for name := range managed.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := managed.Services[name]
		keys := make([]string, 0, len(svc.Vars))
		for key := range svc.Vars {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		for _, key := range keys {
			if existing, exists := result[key]; exists && existing != svc.Vars[key] {
				return nil, fmt.Errorf("cannot flatten service-scoped env var %q from service %q; it conflicts with another env source", key, name)
			}
			result[key] = svc.Vars[key]
		}

		if svc.PortKey != "" && svc.PortVal != "" {
			result[svc.PortKey] = svc.PortVal
		}
	}

	return result, nil
}

// EnvLocalMapping describes a .env.local file to write in the worktree.
type EnvLocalMapping struct {
	RelPath string
	Vars    map[string]string
}

// WriteEnvLocals writes .env.local files into the worktree.
func WriteEnvLocals(mappings []EnvLocalMapping, worktreePath string) error {
	for _, m := range mappings {
		absPath := filepath.Join(worktreePath, m.RelPath)

		if err := os.MkdirAll(filepath.Dir(absPath), 0755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", m.RelPath, err)
		}

		keys := make([]string, 0, len(m.Vars))
		for k := range m.Vars {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var sb strings.Builder
		sb.WriteString("# Generated by grove — do not edit\n")
		for _, k := range keys {
			sb.WriteString(k + "=" + m.Vars[k] + "\n")
		}

		if err := os.WriteFile(absPath, []byte(sb.String()), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", m.RelPath, err)
		}
	}
	return nil
}

// SymlinkEnvFiles creates relative symlinks from the main repo's .env files
// into the worktree. This makes secrets and shared config available without
// copying. Each env file listed in the config is symlinked individually.
func SymlinkEnvFiles(envFiles []string, projectRoot, worktreePath string) error {
	for _, envFile := range envFiles {
		mainAbs := filepath.Join(projectRoot, envFile)
		wtAbs := filepath.Join(worktreePath, envFile)

		if _, err := os.Stat(mainAbs); os.IsNotExist(err) {
			continue
		}

		if err := os.MkdirAll(filepath.Dir(wtAbs), 0755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", envFile, err)
		}

		// Check if symlink already exists and points to the right place
		if target, err := os.Readlink(wtAbs); err == nil {
			expectedRel, relErr := filepath.Rel(filepath.Dir(wtAbs), mainAbs)
			if relErr == nil && target == expectedRel {
				continue
			}
			os.Remove(wtAbs)
		} else if _, err := os.Lstat(wtAbs); err == nil {
			os.Remove(wtAbs)
		}

		relTarget, err := filepath.Rel(filepath.Dir(wtAbs), mainAbs)
		if err != nil {
			return fmt.Errorf("computing relative path for %s: %w", envFile, err)
		}

		if err := os.Symlink(relTarget, wtAbs); err != nil {
			return fmt.Errorf("symlinking %s: %w", envFile, err)
		}
	}
	return nil
}
