// Package env handles environment variable resolution for Grove workspaces.
//
// Resolution order (last wins):
//  1. .env files — symlinked from main repo into worktrees
//  2. .env.local files — generated by grove with branch-specific port assignments
//  3. tmux set-environment — fallback for non-dotenv tools (session mode only)
package env

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/lukemelnik/grove/internal/config"
)

// templatePattern matches {{service.port}} references in env values.
var templatePattern = regexp.MustCompile(`\{\{(\w+)\.port\}\}`)

// ParseEnvFile reads a .env file and returns a map of key-value pairs.
// It handles:
//   - Empty lines (skipped)
//   - Comment lines starting with # (skipped)
//   - KEY=VALUE format
//   - Quoted values (single and double quotes are stripped)
//   - Inline comments after unquoted values
//   - Lines with no = sign (skipped)
func ParseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading env file %s: %w", path, err)
	}
	return ParseEnvContent(string(data))
}

// ParseEnvContent parses the content of a .env file (as a string) into key-value pairs.
func ParseEnvContent(content string) (map[string]string, error) {
	result := make(map[string]string)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Find the first = sign
		eqIdx := strings.Index(line, "=")
		if eqIdx < 0 {
			// No = sign, skip this line
			continue
		}

		key := strings.TrimSpace(line[:eqIdx])
		value := strings.TrimSpace(line[eqIdx+1:])

		if key == "" {
			continue
		}

		// Handle quoted values — preserve content inside quotes verbatim.
		// For unquoted values, strip inline comments (e.g., "value # comment").
		quoted := false
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
				quoted = true
			}
		}
		if !quoted {
			if idx := strings.Index(value, " #"); idx >= 0 {
				value = strings.TrimRight(value[:idx], " ")
			}
		}

		result[key] = value
	}

	return result, nil
}

// ResolveTemplates replaces {{service.port}} references in a string
// using the provided port map (service name -> port number).
// Returns the resolved string and an error if any referenced service is not found.
func ResolveTemplates(value string, ports map[string]int) (string, error) {
	var resolveErr error

	resolved := templatePattern.ReplaceAllStringFunc(value, func(match string) string {
		// Extract the service name from {{service.port}}
		submatch := templatePattern.FindStringSubmatch(match)
		if len(submatch) < 2 {
			return match
		}
		serviceName := submatch[1]
		port, ok := ports[serviceName]
		if !ok {
			resolveErr = fmt.Errorf("unknown service %q in template %q", serviceName, match)
			return match
		}
		return fmt.Sprintf("%d", port)
	})

	return resolved, resolveErr
}

// Resolve computes the final set of environment variables for a worktree.
//
// Parameters:
//   - cfg: the parsed .grove.yml configuration
//   - ports: map of service name to assigned port (from port hashing)
//   - projectRoot: the project root directory (for resolving relative env file paths)
//
// Resolution order (last wins):
//  1. .env files from cfg.EnvFiles
//  2. env block from cfg.Env (with template resolution)
//  3. service port vars (e.g., PORT=4045)
func Resolve(cfg *config.Config, ports map[string]int, projectRoot string) (map[string]string, error) {
	result := make(map[string]string)

	// Step 1: Read all .env files (order matters, later files override earlier ones)
	for _, envFile := range cfg.EnvFiles {
		path := envFile
		if projectRoot != "" && !filepath.IsAbs(path) {
			path = filepath.Join(projectRoot, path)
		}
		vars, err := ParseEnvFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading env file: %w", err)
		}
		for k, v := range vars {
			result[k] = v
		}
	}

	// Step 2: Apply env block from config (with template resolution)
	for k, v := range cfg.Env {
		resolved, err := ResolveTemplates(v, ports)
		if err != nil {
			return nil, fmt.Errorf("resolving template in env var %s: %w", k, err)
		}
		result[k] = resolved
	}

	// Step 3: Apply service port vars (always win over env block)
	for name, svc := range cfg.Services {
		port, ok := ports[name]
		if !ok {
			continue
		}
		result[svc.Env] = fmt.Sprintf("%d", port)
	}

	return result, nil
}

// ManagedVars computes the grove-managed env vars: service ports and
// resolved env block templates. These are the branch-specific values
// written to .env.local files.
func ManagedVars(cfg *config.Config, ports map[string]int) map[string]string {
	result := make(map[string]string)

	for k, v := range cfg.Env {
		resolved, err := ResolveTemplates(v, ports)
		if err == nil {
			result[k] = resolved
		}
	}

	for name, svc := range cfg.Services {
		port, ok := ports[name]
		if !ok {
			continue
		}
		result[svc.Env] = fmt.Sprintf("%d", port)
	}

	return result
}

// EnvLocalMapping describes a .env.local file to write in the worktree.
type EnvLocalMapping struct {
	RelPath string
	Vars    map[string]string
}

// MapManagedToEnvFiles determines which managed vars go in which .env.local file.
// For each env file, it parses the original to find which keys it contains.
// Managed vars whose keys appear in that env file go into its .env.local.
// Managed vars not found in any env file go into the last env file's .env.local.
func MapManagedToEnvFiles(cfg *config.Config, managed map[string]string, projectRoot string) []EnvLocalMapping {
	if len(cfg.EnvFiles) == 0 || len(managed) == 0 {
		return nil
	}

	placed := make(map[string]bool)
	var mappings []EnvLocalMapping

	for _, envFile := range cfg.EnvFiles {
		absPath := envFile
		if projectRoot != "" && !filepath.IsAbs(absPath) {
			absPath = filepath.Join(projectRoot, absPath)
		}

		existing, err := ParseEnvFile(absPath)
		if err != nil {
			continue
		}

		localVars := make(map[string]string)
		for key, val := range managed {
			if _, inFile := existing[key]; inFile && !placed[key] {
				localVars[key] = val
				placed[key] = true
			}
		}

		localPath := envFile + ".local"
		if len(localVars) > 0 {
			mappings = append(mappings, EnvLocalMapping{RelPath: localPath, Vars: localVars})
		}
	}

	// Remaining managed vars not found in any env file go into the last env file's .env.local
	remaining := make(map[string]string)
	for key, val := range managed {
		if !placed[key] {
			remaining[key] = val
		}
	}

	if len(remaining) > 0 {
		lastLocal := cfg.EnvFiles[len(cfg.EnvFiles)-1] + ".local"

		found := false
		for i := range mappings {
			if mappings[i].RelPath == lastLocal {
				for k, v := range remaining {
					mappings[i].Vars[k] = v
				}
				found = true
				break
			}
		}
		if !found {
			mappings = append(mappings, EnvLocalMapping{RelPath: lastLocal, Vars: remaining})
		}
	}

	return mappings
}

// WriteEnvLocals writes .env.local files into the worktree.
func WriteEnvLocals(mappings []EnvLocalMapping, worktreePath string) error {
	for _, m := range mappings {
		absPath := filepath.Join(worktreePath, m.RelPath)

		if err := os.MkdirAll(filepath.Dir(absPath), 0755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", m.RelPath, err)
		}

		keys := make([]string, 0, len(m.Vars))
		for k := range m.Vars {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var sb strings.Builder
		sb.WriteString("# Generated by grove — do not edit\n")
		for _, k := range keys {
			sb.WriteString(k + "=" + m.Vars[k] + "\n")
		}

		if err := os.WriteFile(absPath, []byte(sb.String()), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", m.RelPath, err)
		}
	}
	return nil
}

// SymlinkEnvFiles creates relative symlinks from the main repo's .env files
// into the worktree. This makes secrets and shared config available without
// copying. Each env file listed in the config is symlinked individually.
func SymlinkEnvFiles(envFiles []string, projectRoot, worktreePath string) error {
	for _, envFile := range envFiles {
		mainAbs := filepath.Join(projectRoot, envFile)
		wtAbs := filepath.Join(worktreePath, envFile)

		if _, err := os.Stat(mainAbs); os.IsNotExist(err) {
			continue
		}

		if err := os.MkdirAll(filepath.Dir(wtAbs), 0755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", envFile, err)
		}

		// Check if symlink already exists and points to the right place
		if target, err := os.Readlink(wtAbs); err == nil {
			expectedRel, relErr := filepath.Rel(filepath.Dir(wtAbs), mainAbs)
			if relErr == nil && target == expectedRel {
				continue
			}
			os.Remove(wtAbs)
		} else if _, err := os.Lstat(wtAbs); err == nil {
			os.Remove(wtAbs)
		}

		relTarget, err := filepath.Rel(filepath.Dir(wtAbs), mainAbs)
		if err != nil {
			return fmt.Errorf("computing relative path for %s: %w", envFile, err)
		}

		if err := os.Symlink(relTarget, wtAbs); err != nil {
			return fmt.Errorf("symlinking %s: %w", envFile, err)
		}
	}
	return nil
}
