// Package env handles environment variable resolution for Grove workspaces.
//
// Resolution order (last wins):
//  1. .env files — symlinked from main repo into worktrees
//  2. .env.local files — generated by grove with branch-specific port assignments
//  3. tmux set-environment — fallback for non-dotenv tools (session mode only)
package env

import (
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/lukemelnik/grove/internal/config"
)

// templatePattern matches {{service.port}}, {{branch}}, and {{branch.hash}}
// references in env values. Service names may contain hyphens and underscores.
var (
	templatePattern           = regexp.MustCompile(`\{\{([A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)?)\}\}`)
	unresolvedTemplatePattern = regexp.MustCompile(`\{\{[^{}\r\n]+\}\}`)
)

func branchHash(branch string) string {
	sum := sha1.Sum([]byte(branch))
	return hex.EncodeToString(sum[:])[:12]
}

// ParseEnvFile reads a .env file and returns a map of key-value pairs.
// It handles:
//   - Empty lines (skipped)
//   - Comment lines starting with # (skipped)
//   - KEY=VALUE format
//   - Quoted values (single and double quotes are stripped)
//   - Inline comments after unquoted values
//   - Lines with no = sign (skipped)
func ParseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading env file %s: %w", path, err)
	}
	return ParseEnvContent(string(data))
}

// ParseEnvContent parses the content of a .env file (as a string) into key-value pairs.
func ParseEnvContent(content string) (map[string]string, error) {
	result := make(map[string]string)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Find the first = sign
		eqIdx := strings.Index(line, "=")
		if eqIdx < 0 {
			// No = sign, skip this line
			continue
		}

		key := strings.TrimSpace(line[:eqIdx])
		value := strings.TrimSpace(line[eqIdx+1:])

		if key == "" {
			continue
		}

		// Handle quoted values. For unquoted values, strip inline comments
		// (e.g., "value # comment").
		quoted := false
		if len(value) >= 2 {
			if value[0] == '"' && value[len(value)-1] == '"' {
				unquoted, err := unquoteDoubleEnv(value[1 : len(value)-1])
				if err != nil {
					return nil, fmt.Errorf("parsing %s: %w", key, err)
				}
				value = unquoted
				quoted = true
			} else if value[0] == '\'' && value[len(value)-1] == '\'' {
				value = value[1 : len(value)-1]
				quoted = true
			}
		}
		if !quoted {
			if idx := strings.Index(value, " #"); idx >= 0 {
				value = strings.TrimRight(value[:idx], " ")
			}
		}

		result[key] = value
	}

	return result, nil
}

// ResolveTemplates replaces {{service.port}}, {{branch}}, and {{branch.hash}}
// references in a string using the provided port map and branch name.
// Returns the resolved string and an error if any referenced template is unknown.
func ResolveTemplates(value string, ports map[string]int, branch string) (string, error) {
	var resolveErr error

	resolved := templatePattern.ReplaceAllStringFunc(value, func(match string) string {
		submatch := templatePattern.FindStringSubmatch(match)
		if len(submatch) < 2 {
			return match
		}
		ref := submatch[1]

		if ref == "branch" {
			return branch
		}
		if ref == "branch.hash" {
			return branchHash(branch)
		}

		parts := strings.SplitN(ref, ".", 2)
		if len(parts) == 2 && parts[1] == "port" {
			port, ok := ports[parts[0]]
			if !ok {
				resolveErr = fmt.Errorf("unknown service %q in environment template", parts[0])
				return match
			}
			return fmt.Sprintf("%d", port)
		}

		resolveErr = fmt.Errorf("unknown environment template")
		return match
	})

	if resolveErr != nil {
		return resolved, resolveErr
	}
	if unresolvedTemplatePattern.MatchString(resolved) {
		return resolved, fmt.Errorf("unsupported environment template syntax")
	}
	return resolved, nil
}

// ServiceManagedEnv describes the managed env vars for a single service.
type ServiceManagedEnv struct {
	Name    string
	EnvFile string
	PortKey string
	PortVal string
	Vars    map[string]string
}

// ManagedEnv groups global env vars, unique service port vars, and service-
// scoped env vars so runtime code can write .env.local files without losing
// service ownership.
type ManagedEnv struct {
	Global   map[string]string
	Services map[string]ServiceManagedEnv
}

// SessionEnv returns the session-wide env for tmux fallback injection.
// Only top-level env vars and service port vars are included here; service-
// scoped env vars stay in their service's .env.local file.
func (m *ManagedEnv) SessionEnv() map[string]string {
	result := make(map[string]string, len(m.Global)+len(m.Services))

	for k, v := range m.Global {
		result[k] = v
	}

	names := make([]string, 0, len(m.Services))
	for name := range m.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := m.Services[name]
		if svc.PortKey != "" && svc.PortVal != "" {
			result[svc.PortKey] = svc.PortVal
		}
	}

	return result
}

// EnvLocalMappings builds the .env.local write plan for all configured env
// files. Top-level env vars are written to every .env.local file. Service-
// scoped vars and service port vars are written only to that service's
// env_file.local. Port vars for services without env_file fall back to the
// top-level env_files list using key matching, then the last top-level env file.
func (m *ManagedEnv) EnvLocalMappings(cfg *config.Config, projectRoot string) ([]EnvLocalMapping, error) {
	allEnvFiles := cfg.AllEnvFiles()
	if len(allEnvFiles) == 0 {
		return nil, nil
	}

	mappingIndex := make(map[string]int)
	var mappings []EnvLocalMapping

	addToMapping := func(localPath, key, val string) {
		idx, exists := mappingIndex[localPath]
		if !exists {
			idx = len(mappings)
			mappingIndex[localPath] = idx
			mappings = append(mappings, EnvLocalMapping{RelPath: localPath, Vars: make(map[string]string)})
		}
		mappings[idx].Vars[key] = val
	}

	globalKeys := make([]string, 0, len(m.Global))
	for key := range m.Global {
		globalKeys = append(globalKeys, key)
	}
	sort.Strings(globalKeys)

	for _, envFile := range allEnvFiles {
		localPath := envFile + ".local"
		for _, key := range globalKeys {
			addToMapping(localPath, key, m.Global[key])
		}
	}

	names := make([]string, 0, len(m.Services))
	for name := range m.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	orphanPorts := make(map[string]string)
	for _, name := range names {
		svc := m.Services[name]

		if svc.EnvFile == "" {
			if svc.PortKey != "" && svc.PortVal != "" {
				orphanPorts[svc.PortKey] = svc.PortVal
			}
			continue
		}

		localPath := svc.EnvFile + ".local"
		if svc.PortKey != "" && svc.PortVal != "" {
			addToMapping(localPath, svc.PortKey, svc.PortVal)
		}

		keys := make([]string, 0, len(svc.Vars))
		for key := range svc.Vars {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			addToMapping(localPath, key, svc.Vars[key])
		}
	}

	if len(orphanPorts) > 0 && len(cfg.EnvFiles) > 0 {
		placed := make(map[string]bool)
		for _, envFile := range cfg.EnvFiles {
			absPath := envFile
			if projectRoot != "" && !filepath.IsAbs(absPath) {
				absPath = filepath.Join(projectRoot, absPath)
			}

			existing, err := ParseEnvFile(absPath)
			if err != nil {
				continue
			}

			localPath := envFile + ".local"
			for key, val := range orphanPorts {
				if placed[key] {
					continue
				}
				if _, inFile := existing[key]; inFile {
					addToMapping(localPath, key, val)
					placed[key] = true
				}
			}
		}

		lastLocal := cfg.EnvFiles[len(cfg.EnvFiles)-1] + ".local"
		orphanKeys := make([]string, 0, len(orphanPorts))
		for key := range orphanPorts {
			orphanKeys = append(orphanKeys, key)
		}
		sort.Strings(orphanKeys)
		for _, key := range orphanKeys {
			if !placed[key] {
				addToMapping(lastLocal, key, orphanPorts[key])
			}
		}
	}

	filtered := make([]EnvLocalMapping, 0, len(mappings))
	for _, mapping := range mappings {
		if len(mapping.Vars) == 0 {
			continue
		}
		filtered = append(filtered, mapping)
	}

	return filtered, nil
}

func resolveGlobalEnv(cfg *config.Config, ports map[string]int, branch string) (map[string]string, error) {
	result := make(map[string]string)
	for k, v := range cfg.Env {
		resolved, err := ResolveTemplates(v, ports, branch)
		if err != nil {
			return nil, fmt.Errorf("resolving template in env var %s: %w", k, err)
		}
		result[k] = resolved
	}
	return result, nil
}

// BuildManagedEnv resolves Grove-managed env vars while preserving service
// ownership for service-scoped values.
func BuildManagedEnv(cfg *config.Config, ports map[string]int, branch string) (*ManagedEnv, error) {
	global, err := resolveGlobalEnv(cfg, ports, branch)
	if err != nil {
		return nil, err
	}

	services := make(map[string]ServiceManagedEnv, len(cfg.Services))
	names := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := cfg.Services[name]
		entry := ServiceManagedEnv{
			Name:    name,
			EnvFile: svc.EnvFile,
			PortKey: svc.Port.Env,
			Vars:    make(map[string]string, len(svc.Env)),
		}

		if port, ok := ports[name]; ok {
			entry.PortVal = fmt.Sprintf("%d", port)
		}

		keys := make([]string, 0, len(svc.Env))
		for key := range svc.Env {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		for _, key := range keys {
			resolved, err := ResolveTemplates(svc.Env[key], ports, branch)
			if err != nil {
				return nil, fmt.Errorf("resolving template in service %s env var %s: %w", name, key, err)
			}
			entry.Vars[key] = resolved
		}

		services[name] = entry
	}

	return &ManagedEnv{
		Global:   global,
		Services: services,
	}, nil
}

// Resolve computes the flattened environment variables for a worktree.
//
// Parameters:
//   - cfg: the parsed .grove.yml configuration
//   - ports: map of service name to assigned port (from port hashing)
//   - branch: the branch name (for {{branch}} template resolution)
//   - projectRoot: the project root directory (for resolving relative env file paths)
//
// Resolution order (last wins):
//  1. .env files from cfg.EnvFiles and service env_file fields
//  2. top-level env block (with template resolution)
//  3. service-level env blocks (with template resolution)
//  4. service port vars (e.g., PORT=4045)
func Resolve(cfg *config.Config, ports map[string]int, branch string, projectRoot string) (map[string]string, error) {
	result := make(map[string]string)

	// Step 1: Read all .env files (order matters, later files override earlier ones)
	for _, envFile := range cfg.AllEnvFiles() {
		path := envFile
		if projectRoot != "" && !filepath.IsAbs(path) {
			path = filepath.Join(projectRoot, path)
		}
		vars, err := ParseEnvFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading env file: %w", err)
		}
		for k, v := range vars {
			result[k] = v
		}
	}

	managed, err := BuildManagedEnv(cfg, ports, branch)
	if err != nil {
		return nil, err
	}

	for k, v := range managed.Global {
		result[k] = v
	}

	names := make([]string, 0, len(managed.Services))
	for name := range managed.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		svc := managed.Services[name]
		keys := make([]string, 0, len(svc.Vars))
		for key := range svc.Vars {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		for _, key := range keys {
			if existing, exists := result[key]; exists && existing != svc.Vars[key] {
				return nil, fmt.Errorf("cannot flatten service-scoped env var %q from service %q; it conflicts with another env source", key, name)
			}
			result[key] = svc.Vars[key]
		}

		if svc.PortKey != "" && svc.PortVal != "" {
			result[svc.PortKey] = svc.PortVal
		}
	}

	return result, nil
}

// EnvLocalMapping describes a .env.local file to write in the worktree.
type EnvLocalMapping struct {
	RelPath string
	Vars    map[string]string
}

const generatedEnvLocalMarker = "# Generated by grove — do not edit\n"

var (
	renameFile               = os.Rename
	errOptionalSourceMissing = errors.New("optional canonical source missing")
)

// PreflightEnvLocals validates every generated-local destination without
// mutating the filesystem.
func PreflightEnvLocals(mappings []EnvLocalMapping, worktreePath string) error {
	return writeEnvLocals(mappings, worktreePath, false)
}

// WriteEnvLocals writes .env.local files into the worktree. It only creates or
// replaces Grove-generated regular files with the exact generated marker;
// user-owned regular files, symlinks, and unusual filesystem objects are
// preserved and reported as collisions.
func WriteEnvLocals(mappings []EnvLocalMapping, worktreePath string) error {
	return writeEnvLocals(mappings, worktreePath, true)
}

func writeEnvLocals(mappings []EnvLocalMapping, worktreePath string, apply bool) error {
	root, err := cleanAbsRoot(worktreePath)
	if err != nil {
		return fmt.Errorf("validating worktree root: %w", err)
	}

	type plan struct {
		mapping  EnvLocalMapping
		path     string
		existing os.FileInfo
	}
	plans := make([]plan, 0, len(mappings))
	seen := make(map[string]struct{}, len(mappings))
	for _, m := range mappings {
		if err := validateGeneratedEnvVars(m.Vars); err != nil {
			return fmt.Errorf("validating generated env local %s: %w", m.RelPath, err)
		}
		dst, err := pathInsideRoot(root, m.RelPath)
		if err != nil {
			return fmt.Errorf("invalid env local path %q: %w", m.RelPath, err)
		}
		if _, ok := seen[dst]; ok {
			return fmt.Errorf("duplicate env local destination %q", m.RelPath)
		}
		seen[dst] = struct{}{}
		if err := validateSecureParent(root, filepath.Dir(dst)); err != nil {
			return fmt.Errorf("validating parent for %s: %w", m.RelPath, err)
		}

		var existing os.FileInfo
		info, err := os.Lstat(dst)
		switch {
		case err == nil:
			if info.Mode()&os.ModeSymlink != 0 {
				return fmt.Errorf("refusing to overwrite symlink at %s", m.RelPath)
			}
			if !info.Mode().IsRegular() {
				return fmt.Errorf("refusing to overwrite non-regular file at %s", m.RelPath)
			}
			generated, err := hasGeneratedMarker(dst, info)
			if err != nil {
				return fmt.Errorf("validating existing %s: %w", m.RelPath, err)
			}
			if !generated {
				return fmt.Errorf("refusing to overwrite user-owned env local file at %s", m.RelPath)
			}
			existing = info
		case errors.Is(err, os.ErrNotExist):
			// Missing generated files are created during the apply phase.
		default:
			return fmt.Errorf("inspecting %s: %w", m.RelPath, err)
		}
		plans = append(plans, plan{mapping: m, path: dst, existing: existing})
	}

	if !apply {
		return nil
	}
	for _, p := range plans {
		if err := ensureSecureParent(root, filepath.Dir(p.path)); err != nil {
			return fmt.Errorf("creating parent for %s: %w", p.mapping.RelPath, err)
		}
		content := renderEnvLocal(p.mapping.Vars)
		if err := atomicWriteFile(p.path, []byte(content), 0644, p.existing); err != nil {
			return fmt.Errorf("writing %s: %w", p.mapping.RelPath, err)
		}
	}
	return nil
}

// PreflightEnvFiles validates every configured source and destination without
// mutating the filesystem.
func PreflightEnvFiles(envFiles []string, projectRoot, worktreePath string) error {
	return symlinkEnvFiles(envFiles, projectRoot, worktreePath, false)
}

// SymlinkEnvFiles creates relative symlinks from the main repo's env files into
// the worktree. A genuinely missing configured canonical source is optional and
// skipped, and any existing destination for that missing mapping is untouched.
// All mappings are preflighted before mutation; invalid paths, invalid sources,
// and destination collisions fail without changing any mapping.
func SymlinkEnvFiles(envFiles []string, projectRoot, worktreePath string) error {
	return symlinkEnvFiles(envFiles, projectRoot, worktreePath, true)
}

func symlinkEnvFiles(envFiles []string, projectRoot, worktreePath string, apply bool) error {
	project, err := cleanAbsRoot(projectRoot)
	if err != nil {
		return fmt.Errorf("validating project root: %w", err)
	}
	worktree, err := cleanAbsRoot(worktreePath)
	if err != nil {
		return fmt.Errorf("validating worktree root: %w", err)
	}
	sameRoot, err := sameExistingPath(project, worktree)
	if err != nil {
		return fmt.Errorf("comparing project and worktree roots: %w", err)
	}

	type plan struct {
		rel, src, dst, target string
		existing              os.FileInfo
		existingTarget        string
		apply                 bool
	}
	plans := make([]plan, 0, len(envFiles))
	seen := make(map[string]struct{}, len(envFiles))
	for _, rel := range envFiles {
		src, err := pathInsideRoot(project, rel)
		if err != nil {
			return fmt.Errorf("invalid env file path %q: %w", rel, err)
		}
		dst, err := pathInsideRoot(worktree, rel)
		if err != nil {
			return fmt.Errorf("invalid env file path %q: %w", rel, err)
		}
		if _, ok := seen[dst]; ok {
			return fmt.Errorf("duplicate env file destination %q", rel)
		}
		seen[dst] = struct{}{}

		_, err = validSource(src, rel)
		if errors.Is(err, errOptionalSourceMissing) {
			plans = append(plans, plan{rel: rel})
			continue
		}
		if err != nil {
			return err
		}
		if sameRoot {
			// The validated canonical source is already at the destination. This
			// guard precedes every destination mutation, including directory work.
			plans = append(plans, plan{rel: rel})
			continue
		}
		if err := validateSecureParent(worktree, filepath.Dir(dst)); err != nil {
			return fmt.Errorf("validating parent for %s: %w", rel, err)
		}
		target, err := filepath.Rel(filepath.Dir(dst), src)
		if err != nil {
			return fmt.Errorf("computing relative path for %s: %w", rel, err)
		}

		var existing os.FileInfo
		var existingTarget string
		linfo, err := os.Lstat(dst)
		switch {
		case err == nil:
			if linfo.Mode()&os.ModeSymlink == 0 {
				kind := "non-symlink"
				if linfo.Mode().IsRegular() {
					kind = "regular file"
				}
				return fmt.Errorf("refusing to overwrite existing %s at %s; move it aside or remove it after verifying its contents", kind, rel)
			}
			cur, err := os.Readlink(dst)
			if err != nil {
				return fmt.Errorf("reading symlink %s: %w", rel, err)
			}
			if sameSymlinkTarget(filepath.Dir(dst), cur, src) {
				plans = append(plans, plan{rel: rel})
				continue
			}
			existing = linfo
			existingTarget = cur
		case errors.Is(err, os.ErrNotExist):
			// Missing destinations are created during the apply phase.
		default:
			return fmt.Errorf("inspecting destination %s: %w", rel, err)
		}
		plans = append(plans, plan{
			rel: rel, src: src, dst: dst, target: target,
			existing: existing, existingTarget: existingTarget, apply: true,
		})
	}

	if !apply {
		return nil
	}
	for _, p := range plans {
		if !p.apply {
			continue
		}
		if _, err := validSource(p.src, p.rel); err != nil {
			return fmt.Errorf("revalidating canonical source before mutation: %w", err)
		}
		if err := ensureSecureParent(worktree, filepath.Dir(p.dst)); err != nil {
			return fmt.Errorf("creating parent for %s: %w", p.rel, err)
		}
		if _, err := validSource(p.src, p.rel); err != nil {
			return fmt.Errorf("revalidating canonical source before replacement: %w", err)
		}
		if err := atomicSymlink(p.target, p.dst, p.existing, p.existingTarget); err != nil {
			return fmt.Errorf("symlinking %s: %w", p.rel, err)
		}
	}
	return nil
}

func cleanAbsRoot(root string) (string, error) {
	if strings.TrimSpace(root) == "" {
		return "", fmt.Errorf("empty root")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(filepath.Clean(abs))
	if err != nil {
		return "", err
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return "", fmt.Errorf("%s is not a directory", resolved)
	}
	return filepath.Clean(resolved), nil
}

func sameExistingPath(a, b string) (bool, error) {
	if filepath.Clean(a) == filepath.Clean(b) {
		return true, nil
	}
	aInfo, err := os.Stat(a)
	if err != nil {
		return false, err
	}
	bInfo, err := os.Stat(b)
	if err != nil {
		return false, err
	}
	return os.SameFile(aInfo, bInfo), nil
}

func pathInsideRoot(root, rel string) (string, error) {
	if rel == "" || filepath.IsAbs(rel) {
		return "", fmt.Errorf("must be a non-empty relative path")
	}
	clean := filepath.Clean(rel)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(os.PathSeparator)) {
		return "", fmt.Errorf("must not escape root")
	}
	return filepath.Join(root, clean), nil
}

func validateSecureParent(root, dir string) error {
	return walkSecureParent(root, dir, false)
}

func ensureSecureParent(root, dir string) error {
	return walkSecureParent(root, dir, true)
}

func walkSecureParent(root, dir string, create bool) error {
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return err
	}
	if rel == "." {
		return nil
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
		return fmt.Errorf("parent escapes root")
	}

	cur := root
	parentMissing := false
	for _, part := range strings.Split(rel, string(os.PathSeparator)) {
		cur = filepath.Join(cur, part)
		if parentMissing && !create {
			continue
		}
		info, err := os.Lstat(cur)
		if errors.Is(err, os.ErrNotExist) {
			if !create {
				parentMissing = true
				continue
			}
			if err := os.Mkdir(cur, 0755); err != nil && !errors.Is(err, os.ErrExist) {
				return err
			}
			info, err = os.Lstat(cur)
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("nested destination parent symlink %s is not allowed", rel)
		}
		if !info.IsDir() {
			return fmt.Errorf("destination parent component %s is not a directory", rel)
		}
	}
	return nil
}

func validSource(src, rel string) (os.FileInfo, error) {
	linfo, err := os.Lstat(src)
	if errors.Is(err, os.ErrNotExist) {
		if ancestorErr := validateSourceAncestors(filepath.Dir(src)); ancestorErr != nil {
			return nil, fmt.Errorf("canonical source %s has an invalid parent: %w", rel, ancestorErr)
		}
		return nil, errOptionalSourceMissing
	}
	if err != nil {
		return nil, fmt.Errorf("inspecting canonical source %s: %w", rel, err)
	}
	info, err := os.Stat(src)
	if err != nil {
		if linfo.Mode()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("canonical source %s is a broken, cyclic, or dangling symlink: %w", rel, err)
		}
		return nil, fmt.Errorf("canonical source %s must resolve to a regular file: %w", rel, err)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("canonical source %s is not a regular file", rel)
	}
	return info, nil
}

func validateSourceAncestors(dir string) error {
	volume := filepath.VolumeName(dir)
	root := volume + string(os.PathSeparator)
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return err
	}
	cur := root
	for _, part := range strings.Split(rel, string(os.PathSeparator)) {
		if part == "" || part == "." {
			continue
		}
		cur = filepath.Join(cur, part)
		linfo, err := os.Lstat(cur)
		if errors.Is(err, os.ErrNotExist) {
			// A genuinely absent directory means the configured source is optional.
			return nil
		}
		if err != nil {
			return err
		}
		if linfo.Mode()&os.ModeSymlink != 0 {
			info, err := os.Stat(cur)
			if err != nil {
				return fmt.Errorf("parent symlink %s is broken, cyclic, or dangling: %w", cur, err)
			}
			if !info.IsDir() {
				return fmt.Errorf("parent symlink %s does not resolve to a directory", cur)
			}
			continue
		}
		if !linfo.IsDir() {
			return fmt.Errorf("parent component %s is not a directory", cur)
		}
	}
	return nil
}

func sameSymlinkTarget(dir, target, src string) bool {
	abs := target
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(dir, target)
	}
	a, errA := filepath.EvalSymlinks(abs)
	b, errB := filepath.EvalSymlinks(src)
	return errA == nil && errB == nil && filepath.Clean(a) == filepath.Clean(b)
}

func atomicSymlink(target, dst string, expected os.FileInfo, expectedTarget string) error {
	tmp, err := reserveTempPath(filepath.Dir(dst), "."+filepath.Base(dst)+".grove-link-*")
	if err != nil {
		return err
	}
	if err := os.Symlink(target, tmp); err != nil {
		// The reserved name was already removed. If another actor won the name,
		// do not remove an object that Grove did not create.
		return err
	}
	tmpInfo, err := os.Lstat(tmp)
	if err != nil {
		return err
	}
	staged := true
	defer func() {
		if staged {
			removeOwnedTemp(tmp, tmpInfo)
		}
	}()

	if err := validateSymlinkDestinationUnchanged(dst, expected, expectedTarget); err != nil {
		return err
	}
	if err := renameFile(tmp, dst); err != nil {
		return err
	}
	staged = false
	return nil
}

func reserveTempPath(dir, pattern string) (string, error) {
	f, err := os.CreateTemp(dir, pattern)
	if err != nil {
		return "", err
	}
	name := f.Name()
	if err := f.Close(); err != nil {
		_ = os.Remove(name)
		return "", err
	}
	if err := os.Remove(name); err != nil {
		return "", err
	}
	return name, nil
}

func removeOwnedTemp(path string, expected os.FileInfo) {
	info, err := os.Lstat(path)
	if err == nil && os.SameFile(expected, info) {
		_ = os.Remove(path)
	}
}

func validateSymlinkDestinationUnchanged(path string, expected os.FileInfo, expectedTarget string) error {
	info, err := os.Lstat(path)
	if expected == nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("rechecking destination: %w", err)
		}
		return fmt.Errorf("destination appeared during synchronization; refusing to overwrite it")
	}
	if err != nil {
		return fmt.Errorf("destination changed during synchronization: %w", err)
	}
	if info.Mode()&os.ModeSymlink == 0 || !os.SameFile(expected, info) {
		return fmt.Errorf("destination changed during synchronization; refusing to overwrite it")
	}
	target, err := os.Readlink(path)
	if err != nil {
		return fmt.Errorf("rechecking destination symlink: %w", err)
	}
	if target != expectedTarget {
		return fmt.Errorf("destination symlink changed during synchronization; refusing to overwrite it")
	}
	return nil
}

func validateGeneratedEnvVars(vars map[string]string) error {
	for key, value := range vars {
		if !config.IsValidEnvVarName(key) {
			return fmt.Errorf("invalid environment variable name")
		}
		if strings.ContainsAny(value, "\r\n\x00") {
			return fmt.Errorf("environment values must not contain newlines or NUL bytes")
		}
	}
	return nil
}

func renderEnvLocal(vars map[string]string) string {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var sb strings.Builder
	sb.WriteString(generatedEnvLocalMarker)
	for _, k := range keys {
		sb.WriteString(k + "=" + quoteEnvValue(vars[k]) + "\n")
	}
	return sb.String()
}

func quoteEnvValue(value string) string {
	safe := value != ""
	for _, r := range value {
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || strings.ContainsRune("_./:@+-", r)) {
			safe = false
			break
		}
	}
	if safe {
		return value
	}

	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range value {
		switch r {
		case '\\', '"', '$', '`':
			sb.WriteByte('\\')
		}
		sb.WriteRune(r)
	}
	sb.WriteByte('"')
	return sb.String()
}

func unquoteDoubleEnv(value string) (string, error) {
	var sb strings.Builder
	for i := 0; i < len(value); i++ {
		if value[i] != '\\' {
			sb.WriteByte(value[i])
			continue
		}
		i++
		if i >= len(value) {
			return "", fmt.Errorf("trailing escape")
		}
		switch value[i] {
		case '\\', '"', '$', '`':
			sb.WriteByte(value[i])
		default:
			sb.WriteByte('\\')
			sb.WriteByte(value[i])
		}
	}
	return sb.String(), nil
}

func hasGeneratedMarker(path string, expected os.FileInfo) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	opened, err := f.Stat()
	if err != nil {
		return false, err
	}
	if !opened.Mode().IsRegular() || !os.SameFile(expected, opened) {
		return false, fmt.Errorf("file changed while validating ownership")
	}

	buf := make([]byte, len(generatedEnvLocalMarker))
	n, err := io.ReadFull(f, buf)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return false, err
	}
	return string(buf[:n]) == generatedEnvLocalMarker, nil
}

func validateGeneratedDestinationUnchanged(path string, expected os.FileInfo) error {
	info, err := os.Lstat(path)
	if expected == nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return fmt.Errorf("rechecking destination: %w", err)
		}
		return fmt.Errorf("destination appeared during generation; refusing to overwrite it")
	}
	if err != nil {
		return fmt.Errorf("destination changed during generation: %w", err)
	}
	if !info.Mode().IsRegular() || !os.SameFile(expected, info) {
		return fmt.Errorf("destination changed during generation; refusing to overwrite it")
	}
	generated, err := hasGeneratedMarker(path, info)
	if err != nil {
		return fmt.Errorf("revalidating generated marker: %w", err)
	}
	if !generated {
		return fmt.Errorf("destination is no longer Grove-generated; refusing to overwrite it")
	}
	return nil
}

func atomicWriteFile(path string, data []byte, mode os.FileMode, expected os.FileInfo) error {
	f, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".grove-write-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	tmpInfo, err := f.Stat()
	if err != nil {
		_ = f.Close()
		_ = os.Remove(tmp)
		return err
	}
	renamed := false
	defer func() {
		_ = f.Close()
		if !renamed {
			removeOwnedTemp(tmp, tmpInfo)
		}
	}()
	if _, err := f.Write(data); err != nil {
		return err
	}
	if err := f.Chmod(mode); err != nil {
		return err
	}
	if err := f.Sync(); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := validateGeneratedDestinationUnchanged(path, expected); err != nil {
		return err
	}
	if err := renameFile(tmp, path); err != nil {
		return err
	}
	renamed = true
	return nil
}
